spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouldstudy
    username: clouldstudy
    password: clouldstudy
  application:
    name: serverUser
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka